# Generated by Django 3.1.6 on 2021-02-19 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotelapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='tax',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
