# Generated by Django 3.1.6 on 2021-02-18 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_customuser_phone'),
    ]

    operations = [
        migrations.CreateModel(
            name='Userdetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=200, null=True)),
                ('surname', models.CharField(blank=True, max_length=200, null=True)),
                ('gender', models.CharField(blank=True, max_length=20, null=True)),
                ('dob', models.DateTimeField()),
                ('email', models.CharField(blank=True, max_length=20, null=True)),
                ('PhNumber', models.CharField(blank=True, max_length=20, null=True)),
                ('Id_Proof', models.ImageField(upload_to='')),
            ],
        ),
    ]
