# Generated by Django 3.1.5 on 2021-01-19 05:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField()),
                ('category', models.CharField(choices=[('YAC', 'AC'), ('NAC', 'NON-AC'), ('DEL', 'DELIXE'), ('KIN', 'KING'), ('QUE', 'QUEEN')], max_length=3)),
                ('bed', models.IntegerField()),
                ('Capacity', models.IntegerField()),
            ],
        ),
    ]
