# Generated by Django 3.1.5 on 2021-01-19 07:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_booking'),
    ]

    operations = [
        migrations.CreateModel(
            name='cities',
            fields=[
                ('c_id', models.AutoField(primary_key=True, serialize=False)),
                ('city', models.CharField(blank=True, max_length=150, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Hotels',
            fields=[
                ('h_id', models.AutoField(primary_key=True, serialize=False)),
                ('h_name', models.CharField(blank=True, max_length=300, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='room',
            name='price',
            field=models.IntegerField(default='1250'),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='popularlocations',
            fields=[
                ('p_id', models.AutoField(primary_key=True, serialize=False)),
                ('places', models.CharField(blank=True, max_length=150, null=True)),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.cities')),
            ],
        ),
    ]
