# Generated by Django 3.1.5 on 2021-01-19 07:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_auto_20210119_1305'),
    ]

    operations = [
        migrations.AddField(
            model_name='hotels',
            name='location',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, to='user.popularlocations'),
            preserve_default=False,
        ),
    ]
