# Generated by Django 3.1.5 on 2021-01-19 07:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_room_hotel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='hotel',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, to='user.hotels'),
            preserve_default=False,
        ),
    ]
