# Generated by Django 3.1.5 on 2021-01-20 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0007_auto_20210120_0829'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='image',
            field=models.FileField(blank=True, upload_to=''),
        ),
    ]
