# Generated by Django 3.1.5 on 2021-01-20 17:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0009_images'),
    ]

    operations = [
        migrations.RenameField(
            model_name='images',
            old_name='image',
            new_name='image_1',
        ),
        migrations.AddField(
            model_name='images',
            name='image_2',
            field=models.FileField(blank=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='images',
            name='image_3',
            field=models.FileField(blank=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='images',
            name='image_5',
            field=models.FileField(blank=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='images',
            name='room',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='user.room'),
        ),
    ]
