# Generated by Django 3.1.5 on 2021-01-20 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0010_auto_20210120_2242'),
    ]

    operations = [
        migrations.AlterField(
            model_name='images',
            name='image_2',
            field=models.FileField(upload_to=''),
        ),
        migrations.AlterField(
            model_name='images',
            name='image_3',
            field=models.FileField(upload_to=''),
        ),
        migrations.AlterField(
            model_name='images',
            name='image_5',
            field=models.FileField(upload_to=''),
        ),
    ]
