# Generated by Django 3.1.5 on 2021-01-20 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0011_auto_20210120_2243'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='status',
            field=models.BooleanField(default=False),
        ),
    ]
