# Generated by Django 3.1.5 on 2021-01-22 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0012_booking_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='hotels',
            name='address',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='hotels',
            name='phone_no',
            field=models.IntegerField(blank=True, default=123456789),
            preserve_default=False,
        ),
    ]
