# Generated by Django 3.1.5 on 2021-01-22 17:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0013_auto_20210122_2242'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='popularlocations',
            name='city',
        ),
        migrations.DeleteModel(
            name='cities',
        ),
    ]
