# Generated by Django 3.1.5 on 2021-01-22 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0014_auto_20210122_2256'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hotels',
            name='phone_no',
            field=models.CharField(max_length=12),
        ),
    ]
