# Generated by Django 3.1.5 on 2021-01-24 06:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0015_auto_20210122_2309'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='room_categories',
            name='hotel',
        ),
    ]
