# Generated by Django 3.1.5 on 2021-01-24 11:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0016_remove_room_categories_hotel'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Booking',
        ),
    ]
