# Generated by Django 3.1.5 on 2021-01-24 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0017_delete_booking'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='room',
            name='category',
        ),
        migrations.RemoveField(
            model_name='room',
            name='no_bed',
        ),
        migrations.RemoveField(
            model_name='room',
            name='no_guest',
        ),
        migrations.RemoveField(
            model_name='room',
            name='t_number',
        ),
        migrations.RemoveField(
            model_name='room',
            name='title',
        ),
        migrations.AddField(
            model_name='room',
            name='description',
            field=models.CharField(blank=True, max_length=1000),
        ),
        migrations.AddField(
            model_name='room',
            name='discount',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='room',
            name='image1',
            field=models.FileField(blank=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='room',
            name='image2',
            field=models.FileField(blank=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='room',
            name='image3',
            field=models.FileField(blank=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='room',
            name='room_no',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='room',
            name='room_type',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='room',
            name='tax',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='room',
            name='price',
            field=models.FloatField(),
        ),
        migrations.DeleteModel(
            name='Images',
        ),
        migrations.DeleteModel(
            name='Room_categories',
        ),
    ]
