# Generated by Django 3.1.5 on 2021-01-24 13:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0018_auto_20210124_1815'),
    ]

    operations = [
        migrations.CreateModel(
            name='room_mag',
            fields=[
                ('rm_id', models.AutoField(primary_key=True, serialize=False)),
                ('room_features', models.CharField(blank=True, max_length=50, null=True)),
                ('r_no', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.room')),
            ],
        ),
    ]
