# Generated by Django 3.1.5 on 2021-01-25 07:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0019_room_mag'),
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('b_id', models.AutoField(primary_key=True, serialize=False)),
                ('persion_name', models.CharField(max_length=500)),
                ('Phone_number', models.CharField(max_length=10)),
                ('email', models.CharField(max_length=250)),
                ('check_in', models.DateTimeField()),
                ('check_out', models.DateTimeField()),
                ('payment', models.CharField(max_length=50)),
                ('status', models.BooleanField(default=False)),
            ],
        ),
        migrations.AlterField(
            model_name='room',
            name='description',
            field=models.TextField(default=''),
        ),
        migrations.DeleteModel(
            name='room_mag',
        ),
        migrations.AddField(
            model_name='booking',
            name='room_no',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.room'),
        ),
    ]
